name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # REMOVED: "Get changed files" step
          
    - name: Set up Docker Buildx
      # REMOVED: "if" condition
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      # REMOVED: "if" condition
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD}}
   
    - name: Build and push Docker image
      # REMOVED: "if" condition
      run: |
          docker buildx build --push \
            --build-arg AIRFLOW_WWW_USER_PASSWORD=${{ secrets.AIRFLOW_WWW_USER_PASSWORD }} \
            --build-arg AIRFLOW_WWW_USER_USERNAME=${{ secrets.AIRFLOW_WWW_USER_USERNAME }} \
            --build-arg API_KEY=${{ secrets.API_KEY }} \
            --build-arg CELERY_BACKEND_NAME=${{ secrets.CELERY_BACKEND_NAME }} \
            --build-arg CELERY_BACKEND_PASSWORD=${{ secrets.CELERY_BACKEND_PASSWORD }} \
            --build-arg CELERY_BACKEND_USERNAME=${{ secrets.CELERY_BACKEND_USERNAME }} \
            --build-arg ELT_DATABASE_NAME=${{ secrets.ELT_DATABASE_NAME }} \
            --build-arg ELT_DATABASE_PASSWORD=${{ secrets.ELT_DATABASE_PASSWORD }} \
            --build-arg ELT_DATABASE_USERNAME=${{ secrets.ELT_DATABASE_USERNAME }} \
            --build-arg FERNET_KEY=${{ secrets.FERNET_KEY }} \
            --build-arg METADATA_DATABASE_NAME=${{ secrets.METADATA_DATABASE_NAME }} \
            --build-arg METADATA_DATABASE_PASSWORD=${{ secrets.METADATA_DATABASE_PASSWORD }} \
            --build-arg METADATA_DATABASE_USERNAME=${{ secrets.METADATA_DATABASE_USERNAME }} \
            --build-arg POSTGRES_USER=${{ secrets.POSTGRES_CONN_USERNAME }} \
            --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_CONN_PASSWORD }} \
            --build-arg POSTGRES_CONN_HOST=${{ secrets.POSTGRES_CONN_HOST }} \
            --build-arg POSTGRES_CONN_PASSWORD=${{ secrets.POSTGRES_CONN_PASSWORD }} \
            --build-arg POSTGRES_CONN_PORT=${{ secrets.POSTGRES_CONN_PORT }} \
            --build-arg POSTGRES_CONN_USERNAME=${{ secrets.POSTGRES_CONN_USERNAME }} \
            --build-arg AIRFLOW_UID=${{ vars.AIRFLOW_UID }} \
            --build-arg CHANNEL_HANDLE=${{ vars.CHANNEL_HANDLE }} \
            --build-arg DOCKERHUB_NAMESPACE=${{ vars.DOCKERHUB_NAMESPACE }} \
            --build-arg DOCKERHUB_REPOSITORY=${{ vars.DOCKERHUB_REPOSITORY }} \
            --build-arg DOCKERHUB_USERNAME=${{ vars.DOCKERHUB_USERNAME }} \
            --tag ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest \
            --tag ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.DOCKERHUB_REPOSITORY }}:${{ github.sha }} \
            .

  unit-and-integration-and-e2e-tests:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    env:
      AIRFLOW_WWW_USER_PASSWORD: ${{ secrets.AIRFLOW_WWW_USER_PASSWORD }}
      AIRFLOW_WWW_USER_USERNAME: ${{ secrets.AIRFLOW_WWW_USER_USERNAME }}
      API_KEY: ${{ secrets.API_KEY }}
      CELERY_BACKEND_NAME: ${{ secrets.CELERY_BACKEND_NAME }}
      CELERY_BACKEND_PASSWORD: ${{ secrets.CELERY_BACKEND_PASSWORD }}
      CELERY_BACKEND_USERNAME: ${{ secrets.CELERY_BACKEND_USERNAME }}
      ELT_DATABASE_NAME: ${{ secrets.ELT_DATABASE_NAME }}
      ELT_DATABASE_PASSWORD: ${{ secrets.ELT_DATABASE_PASSWORD }}
      ELT_DATABASE_USERNAME: ${{ secrets.ELT_DATABASE_USERNAME }}
      FERNET_KEY: ${{ secrets.FERNET_KEY }}
      METADATA_DATABASE_NAME: ${{ secrets.METADATA_DATABASE_NAME }}
      METADATA_DATABASE_PASSWORD: ${{ secrets.METADATA_DATABASE_PASSWORD }}
      METADATA_DATABASE_USERNAME: ${{ secrets.METADATA_DATABASE_USERNAME }}
      POSTGRES_USER: ${{ secrets.POSTGRES_CONN_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_CONN_PASSWORD }}
      POSTGRES_CONN_HOST: ${{ secrets.POSTGRES_CONN_HOST }}
      POSTGRES_CONN_PASSWORD: ${{ secrets.POSTGRES_CONN_PASSWORD }}
      POSTGRES_CONN_PORT: ${{ secrets.POSTGRES_CONN_PORT }}
      POSTGRES_CONN_USERNAME: ${{ secrets.POSTGRES_CONN_USERNAME }}
      AIRFLOW_UID: ${{ vars.AIRFLOW_UID }}
      CHANNEL_HANDLE: ${{ vars.CHANNEL_HANDLE }}
      DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
      DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # REMOVED: "Get changed files" step

    - name: Login to Docker Hub
      # REMOVED: "if" condition
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD}}

    - name: Set up Docker Compose
      # REMOVED: "if" condition
      run: |
        docker-compose up -d
        
    - name: Run Unit and Integration Tests
      # REMOVED: "if" condition
      run: |
        docker exec -t airflow-worker sh -c "pytest tests/ -v"
        
    - name: Run E2E Tests
      # REMOVED: "if" condition
      run: |
        DAG_NAMES=("produce_json" "update_db" "data_quality")
        for DAG_NAME in "${DAG_NAMES[@]}"; do
          docker exec -t airflow-worker sh -c "airflow dags test $DAG_NAME"
        done
        
    - name: Stop Docker Compose
      # REMOVED: "if" condition
      run: |
        docker-compose down